### ISSUE TITLE
Error 429: Token exchange failed

### ISSUE THREAD

**Issue by dtmichel** [skodaconnect/skodaconnect#100] opened 2023-11-04 21:20 UTC
Since todays Skoda Connect outage I receive an error 429 with the DEBUG error message „Token exchange failed“.

This happens with TOKENS set and with TOKENS = NONE.

It appears that it is not possible to get a TECHNICAL token.

The MySkoda app is working again meanwhile.

**Comment by kambiumdt** [comment] 2023-11-04 21:34
on my side:

skodaconnect.connection] Could not refresh tokens: 0, message='Attempt to decode JSON with unexpected mimetype: text/plain', url=URL('https://api.connect.skoda-auto.cz/api/v1/authentication/token/refresh?systemId=CONNECT')

**Comment by dvx76** [comment] 2023-11-04 21:37
Duplicate of https://github.com/skodaconnect/homeassistant-skodaconnect/issues/227

**Closed by dvx76** 2023-11-04 21:37 UTC
